Fix: GH workflows fail due to download-artifact deprecation
Error: This request has been automatically failed because it uses a deprecated version of `actions/download-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

https://github.com/DataBiosphere/azul/actions/runs/12814751804/job/35733083557