Fix: GH workflows fail due to upload-artifact deprecation
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

https://github.com/DataBiosphere/azul/actions/runs/12814283218/job/35730339866