Fix: Invalid resource name during `make deploy`
Regression from 8c4ff44a

https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/57342
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/109690

Only occurs when log forwarding is enabled

python api_gateway.tf.json.template.py api_gateway.tf.json
Traceback (most recent call last):
  File "/builds/ucsc/azul/terraform/api_gateway.tf.json.template.py", line 122, in <module>
    emit_tf({
  File "/builds/ucsc/azul/src/azul/terraform.py", line 160, in emit_tf
    emit(_transform_tf(config, tag_resources=tag_resources))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/terraform.py", line 261, in _transform_tf
    _tagged_resource(resource_type, resource_name, resource)
  File "/builds/ucsc/azul/src/azul/terraform.py", line 279, in _tagged_resource
    'tags': _tags(resource_type, resource_name, tags)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/terraform.py", line 331, in _tags
    'name': config.qualified_resource_name(resource_name),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/__init__.py", line 561, in qualified_resource_name
    self._validate_term(resource_name)
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1371, in _validate_term
    require(cls._is_valid_term(term),
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1849, in require
    reject(not condition, *args, exception=exception)
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1869, in reject
    raise exception(*args)
azul.RequirementError: Term is either too short, too long or contains invalid characters: 'indexer_forward_alb_logs-s3event'
make[1]: *** [../common.mk:119: api_gateway.tf.json] Error 1
make[1]: Leaving directory '/builds/ucsc/azul/terraform'
make: *** [Makefile:114: auto_terraform] Error 2
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1